# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
# Azure service connection established during pipeline creation
  azureSubscription: 'Pay-As-You-Go'
  appName: mat-function-app
  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)




    - task: AzureFunctionApp@1 
      inputs:
        azureSubscription: 'Pay-As-You-Go'
        appType: functionAppLinux
        appName: $(mat-function-app)
        package: $(System.ArtifactsDirectory)/**/*.zip